package com.zufar.icedlatte.payment.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum PaymentStatus {

    PAYMENT_METHOD_IS_REQUIRED("PAYMENT_METHOD_IS_REQUIRED",
            "PAYMENT_METHOD_IS_REQUIRED"),

    PAYMENT_CONFIRMATION_IS_REQUIRED("PAYMENT_CONFIRMATION_IS_REQUIRED",
            "PAYMENT_CONFIRMATION_IS_REQUIRED"),

    PAYMENT_CAPTURE_IS_REQUIRED("PAYMENT_CAPTURE_IS_REQUIRED",
            "PAYMENT_CAPTURE_IS_REQUIRED"),

    PAYMENT_ACTION_IS_REQUIRED("PAYMENT_ACTION_IS_REQUIRED",
            "PAYMENT_ACTION_IS_REQUIRED"),

    PAYMENT_IS_FAILED("PAYMENT_IS_FAILED",
            "PAYMENT_IS_FAILED"),

    PAYMENT_IN_PROCESSING("PAYMENT_IN_PROCESSING",
            "PAYMENT_IN_PROCESSING"),

    PAYMENT_IS_CANCELED("PAYMENT_IS_CANCELED",
            "PAYMENT_IS_CANCELED"),

    PAYMENT_IS_SUCCEEDED("PAYMENT_IS_SUCCEEDED",
            "PAYMENT_IS_SUCCEEDED");

    private final String status;
    private final String description;
}

