FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /usr/app

ADD . /usr/app

ARG APP_VERSION
ARG APP_PROFILE

RUN mvn versions:set-property -Dproperty=project.version -DnewVersion=${APP_VERSION} && \
    mvn package -P${APP_PROFILE} -DskipTests

FROM eclipse-temurin:17-jre-jammy 
WORKDIR /usr/app

COPY --from=build /usr/app/target/*.jar /usr/app/app.jar

CMD ["java", "-jar", "/usr/app/app.jar"]