version: '3.9'

networks:
  iced-latte-network:
    name: iced-latte-network

services:
  latte-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: latte-backend
    ports:
      - '8083:8083'
    networks:
      - iced-latte-network
