version: '3.9'

networks:
  online-store-network:
    name: '${DOCKER_COMPOSE_NETWORK}'
    external: true

services:
  online-store-app:
    image: '${DOCKER_HUB}/online-store:${DOCKER_TAG}'
    container_name: online-store-app
    env_file:
      - .env
    build:
      context: .
    ports:
      - '${APP_SERVER_PORT}:${APP_SERVER_PORT}'
    networks:
      - '${DOCKER_COMPOSE_NETWORK}'