server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

spring:
  output:
    ansi:
      enabled: never
  liquibase:
    drop-first: false

management:
  endpoint:
    health:
      show-details: when-authorized
  tracing:
    sampling:
      probability: 0.1

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
