-- AI-generated product summaries — generated once, never regenerated
-- Run: AiProductSummaryGenerator

UPDATE product SET ai_summary = 'Customers have mixed feelings about the Americano, with some appreciating its simplicity and others finding it stale or poorly made.' WHERE id = 'e6a4d7f2-d40e-4e5f-93b8-5d56ce6724c5';
UPDATE product SET ai_summary = 'Customers generally appreciate the quality and consistency of the lattes, though some express disappointment with occasional issues like temperature and flavor.' WHERE id = '1e5b295f-8f50-4425-90e9-8b590a27b3a9';
UPDATE product SET ai_summary = 'Customers generally express a positive sentiment towards the coffee, appreciating its quality and seasonal flavors, though some find the spice overpowering or artificial.' WHERE id = 'aa1d3e8f-9866-4e07-bc61-b5d8c2a3df4b';
UPDATE product SET ai_summary = 'Customers have mixed feelings, enjoying the rich flavors but expressing concerns about sweetness and quality.' WHERE id = '418499f3-d951-40bf-9414-5cb90ab21ecb';
UPDATE product SET ai_summary = 'Customers have mixed feelings, praising some espressos for their quality while expressing disappointment in others for being over or under-extracted.' WHERE id = 'ad0ef2b7-816b-4a11-b361-dfcbe705fc96';
UPDATE product SET ai_summary = 'Customers have mixed feelings, with some enjoying the balance and texture while others find it lacking in boldness and value.' WHERE id = '46f97165-00a7-4b45-9e5c-09f8168b0047';
UPDATE product SET ai_summary = 'Customers generally express satisfaction with the coffee quality, though some find the flat white inconsistent in flavor and texture.' WHERE id = 'fa1e12ff-67e4-42d5-bf45-c43576890f8a';
UPDATE product SET ai_summary = 'Customers generally appreciate the refreshing qualities of the drink but feel that the lemon flavor often overpowers the tea.' WHERE id = '123f7a2d-cb34-4e5f-9a1d-4e4b456a03a7';
UPDATE product SET ai_summary = 'Customers express a mix of appreciation for the quality and balance of the coffee, but some are disappointed by the portion size and value for money.' WHERE id = '3e9c1f94-ee3c-4e0b-9a6e-bb6e9c61c6f5';
UPDATE product SET ai_summary = 'Customers have mixed feelings, appreciating the smoothness of some cold brews while expressing disappointment in others for being weak or stale.' WHERE id = '3ea8e601-24c9-49b1-8c65-8db8b3a5c7a3';
UPDATE product SET ai_summary = 'Customers have mixed feelings, appreciating the unique texture and experience but often finding it overpriced and not worth a repeat purchase.' WHERE id = 'eec8a1d8-4864-4c1b-aa8b-dedfddc6e356';
UPDATE product SET ai_summary = 'Customers generally appreciate the strong and authentic flavors, though some express concerns about sediment and grit in the drink.' WHERE id = 'e0323d1b-1169-4a0e-8d7b-07ff3bfe7f7e';
UPDATE product SET ai_summary = 'Customers have mixed feelings, with many enjoying the strong caffeine boost while others find the flavor and intensity overwhelming.' WHERE id = 'e70f1d94-d55f-4e0e-8a6b-28e2ca3c6c34';
UPDATE product SET ai_summary = 'Customers generally enjoy the flavor and warmth of the drink, but some find it overly sweet or artificial.' WHERE id = 'b5faee5d-6e6d-4319-ba9f-8d1bf7ee3f63';
UPDATE product SET ai_summary = 'Customers have mixed feelings about the matcha, praising its quality and calming effects while also noting issues with flavor strength and texture.' WHERE id = '25a8e8c1-37ba-4a8b-927f-5f1b4b5b5c3c';
UPDATE product SET ai_summary = 'Customers generally express a positive sentiment towards the hot chocolate, praising its rich flavor and comforting qualities, though some note issues with sweetness and temperature.' WHERE id = '4e9a7d28-5e40-4b14-bc72-a5d1b547c3d0';
UPDATE product SET ai_summary = 'Customers have mixed feelings, with some loving the product while others find it unremarkable or poorly executed.' WHERE id = 'cc0b6e5d-71f1-44cd-8a5b-1bdb978b5ca6';
UPDATE product SET ai_summary = 'Customers have mixed feelings, with some praising the flavor and presentation while others express disappointment with quality issues.' WHERE id = 'eedc6cde-1e80-4ebf-a9d1-8e5e4eb2cacf';
UPDATE product SET ai_summary = 'Customers generally appreciate the smoothness and quality of the coffee, but opinions on the vanilla flavor are mixed, with some finding it delightful and others considering it weak or artificial.' WHERE id = 'fc88cd5d-5049-4b00-8d88-df1d9b4a3ce1';
UPDATE product SET ai_summary = 'Customers have mixed feelings about the chocolate and peppermint flavor, with many enjoying it while others find the peppermint overpowering.' WHERE id = 'b183776e-6c3b-459a-bb3a-e93a4c8e4e56';
UPDATE product SET ai_summary = 'Customers have mixed feelings about the hazelnut flavor, with some enjoying its smoothness while others find it too subtle or synthetic.' WHERE id = 'c3f45eec-18d8-43e0-9d7b-d85a4a9b6bda';
UPDATE product SET ai_summary = 'Customers generally appreciate the creamy texture and flavor of the dairy-free latte, though some prefer regular milk and find the oat flavor too strong.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000001';
UPDATE product SET ai_summary = 'Customers generally find the coffee addictive and refreshing, though some note it can be overly sweet and gritty at times.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000002';
UPDATE product SET ai_summary = 'Customers generally appreciate the unique and indulgent pistachio flavor, though some find it lacking in intensity and richness.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000003';
UPDATE product SET ai_summary = 'Customers generally appreciate the unique combination of matcha and espresso, finding it adventurous and delicious, though some feel the flavors clash.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000004';
UPDATE product SET ai_summary = 'Customers generally appreciate the relaxing and pleasant flavors of the lavender and honey coffee, though some find the lavender too strong.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000005';
UPDATE product SET ai_summary = 'Customers generally appreciate the unique combination of chai and espresso, enjoying its bold flavors and energizing qualities, though some find it too intense for regular consumption.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000006';
UPDATE product SET ai_summary = 'Customers generally enjoy the tropical and refreshing flavors of the cold brew with toasted coconut cream, though some find the coconut too thick or sweet.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000007';
UPDATE product SET ai_summary = 'Customers generally find the cold foam and salted caramel drinks indulgent and satisfying, though some note the high price and richness may not suit everyday consumption.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000008';
UPDATE product SET ai_summary = 'Customers generally find the cascara to be a unique and intriguing beverage with a complex flavor profile, though some consider it an acquired taste.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000009';
UPDATE product SET ai_summary = 'Customers generally find the drink visually stunning and delicious, though some feel the flavors can be overly sweet or compete with each other.' WHERE id = 'd1a2b3c4-0001-4000-8000-000000000010';
UPDATE product SET ai_summary = 'Customers have mixed feelings, appreciating the foam and taste in some instances while expressing disappointment over bitterness and temperature issues.' WHERE id = 'a3c4d3f7-1172-4fb2-90a9-59b13b35dfc6';
UPDATE product SET ai_summary = 'Customers have mixed feelings, appreciating the refreshing quality but expressing concerns about dilution and flavor strength.' WHERE id = '6d77f8a9-e640-4d2e-ba2c-b7db8ab2c123';
UPDATE product SET ai_summary = 'Customers have mixed feelings about the espresso and ice cream combination, appreciating the concept but often criticizing the sweetness and portion size.' WHERE id = 'ba5f15c4-1f72-4b97-b9cf-4437e5c6c2fa';
UPDATE product SET ai_summary = 'Customers generally find the coffee to be overly sweet and more like a dessert, with mixed opinions on texture and enjoyment.' WHERE id = '7edf3a1e-c391-4d76-9002-2f0dd3e9c6e9';
UPDATE product SET ai_summary = 'Customers have mixed feelings about the caramel flavor, with some enjoying its sweetness while others find it overpowering and overly sweet.' WHERE id = '5efb7cfd-744b-4af9-b713-ef8d30abf628';
