openapi: "3.0.3"

info:
  title: "Iced Latte Product's Rating API"
  description: "API allows users to add a new rating to a product."
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://iced-latte.uk/backend"
    description: "Production server"

tags:
  - name: "Product Rating"
    description: "Operations related to product's rating"

paths:
  /api/v1/products/{productId}/ratings/{rating}:
    post:
      tags:
        - "Product Rating"
      summary: "Add a new product's rating by authorized user. If rating exists, it will be overridden"
      operationId: "addNewProductRating"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of the product to get rating for"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "rating"
          in: "path"
          description: "Rating value"
          required: true
          schema:
            type: "integer"
            minimum: 1
            maximum: 5
      responses:
        "200":
          description: "Product's rating added successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductRatingDto"
        "401":
          description: "Unauthorized access"
        "404":
          description: "Product was not found"
        "500":
          description: "Internal server error"

  /api/v1/products/{productId}/ratings/statistics:
    get:
      tags:
        - "Product Rating"
      summary: "Get Product Review and Rating statistics: average rating, count of reviews, ratings map. Endpoint is available for unauthorized users"
      operationId: "getRatingAndReviewStat"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID of the product to get rating for"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "Average product rating retrieved successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductReviewRatingStats"
        "404":
          description: "Product was not found"
        "500":
          description: "Internal server error"

components:
  schemas:
    ProductRatingDto:
      type: object
      properties:
        productId:
          type: string
          format: "uuid"
        rating:
          type: "integer"
      required:
        - productId
        - rating

    ProductReviewRatingStats:
      type: object
      properties:
        productId:
          type: string
          format: "uuid"
        rating:
          type: "number"
          format: "double"
        reviewCount:
          type: "integer"
          format: "int32"
        ratingMap:
          $ref: "#/components/schemas/RatingMap"
      required:
        - productId
        - rating
        - reviewCount
        - ratingMap

    RatingMap:
      type: object
      properties:
        5:
          type: "integer"
          format: "int32"
          default: 0
        4:
          type: "integer"
          format: "int32"
          default: 0
        3:
          type: "integer"
          format: "int32"
          default: 0
        2:
          type: "integer"
          format: "int32"
          default: 0
        1:
          type: "integer"
          format: "int32"
          default: 0
      required:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"