openapi: "3.0.3"

info:
  title: "Iced Latte Security API"
  description: "API for accessing security and related operations in the Iced-Latte platform"
  version: "1.0.0"
  contact:
    name: "Iced Latte Support"
    email: "zufar.sunagatov@gmail.com"

servers:
  - url: "http://localhost:8083"
    description: "Local development server"
  - url: "https://dev.api.it-sl.ru"
    description: "Production server"

tags:
  - name: "Security"
    description: "An API for user registration and authentication"

paths:
  /api/v1/auth/register:
    post:
      tags:
        - "Security"
      summary: "Register a user"
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserRegistrationResponse"

  /api/v1/auth/authenticate:
    post:
      tags:
        - "Security"
      summary: "Authenticate a user"
      operationId: "authenticate"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthenticationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserAuthenticationResponse"

components:
  schemas:
    UserRegistrationRequest:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"

    UserRegistrationResponse:
      type: "object"
      properties:
        token:
          type: "string"

    UserAuthenticationRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"

    UserAuthenticationResponse:
      type: "object"
      properties:
        token:
          type: "string"