server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions-cloud-containers.yaml

clients:
  - url: ${GRAFANA_CLOUD_LOKI_URL}
    basic_auth:
      username: ${GRAFANA_CLOUD_LOKI_USERNAME}
      password: ${GRAFANA_CLOUD_LOKI_TOKEN}
    external_labels:
      environment: ${OBSERVABILITY_ENVIRONMENT}

scrape_configs:
  - job_name: iced-latte-docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'compose_project'
