# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Continius Integration pipeline

on:
  pull_request:
    branches:
      - development
      - Gusmanov
      - test-branch
    types:
      - closed


jobs:
  build:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - run: |
        echo The PR was merged