name: Continius Integration Pipeline

on:
  pull_request:
    branches:
      - development
      - Gusmanov
    types:
      - closed

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker Image
      run: |
        docker login
        docker build -t .
        docker-compose run
        docker push ${image.name}

  