name: Continius Integration Pipeline

on:
  pull_request:
    branches:
      - development
      - Gusmanov
    types:
      - closed

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker Image
      run: |
        docker login -u ${DOCKERHUB_USERNAM} -p ${DOCKERHUB_PASSWORD}
        docker build -t ${HUB}/test_ci:${TAG} .
        docker push ${HUB}/test_ci:${TAG}

  