name: Continuous Integration Pipeline

on:
  pull_request:
    branches:
      - development
      - Gusmanov
    types:
      - closed

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker Image
      run: |
        docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
        docker build -t zufarexplainedit/test_ci:latest .
        docker push zufarexplainedit/test_ci:latest