name: Dev PR Build and Test Pipeline

on:
  pull_request:
    branches:
      - development

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn -B package -Pdev --file pom.xml

      - name: Generate test coverage report
        run: mvn jacoco:report --file pom.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
