name: Dev PR Build and Test Pipeline

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -Pdev -DskipTests --file pom.xml

  test:
    name: Test Job
    needs: build
    runs-on: ubuntu-latest

    env:
      APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
      APP_JWT_EXPIRATION_TIME: 604800000

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      - name: Run unit tests
        run: mvn test -Pdev --file pom.xml
